id: DF78EFB77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-21T06:56:21+00:00'
last_modified: '2022-05-30T06:23:48.462411+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e134:
      image_group_id: I1PD95959
      title: སློབ་དཔོན་པདྨ་དགེ་བསྙེན་གྱིས་འཇིག་རྟེན་དབང་ཕྱུག་ལས་གྲུབ་པ་ཐོབ་པའི་ལོ་རྒྱུས།
      total_pages: 1872
      order: 114
      base_file: e134.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
