id: P9A1F0FC9
initial_creation_type: ocr
source_metadata:
  volumes:
    7d6d160aede14e8096c071525c05bb74:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: སློབ་དཔོན་པདྨ་དགེ་བསྙེན་གྱིས་འཇིག་རྟེན་དབང་ཕྱུག་ལས་གྲུབ་པ་ཐོབ་པའི་ལོ་རྒྱུས།
      total_pages: 1872
      volume_number: 114
